### ISSUE TITLE
Source code for homepage/interior page forms and links

### ISSUE THREAD

**Issue by willbunnett** [jakewelchert/legit-action-full-stie#11]
Source to hardcode into homepage/interior page join and contribute submissions and links:

org_hp_lb

**Comment by jakewelchert** [comment]
@willbunnett Just double-checking on this. I replaced this for the signup and got an error like the page wasn't created yet in ActionKit. Or, am I mistaken and this is supposed to be the refcode? Thanks!

**Comment by willbunnett** [comment]
@jakewelchert This is supposed to be a refcode for ActBlue links and a source code for ActionKit forms/form links.

**Comment by jakewelchert** [comment]
Resolved.

**Comment by willbunnett** [comment]
@jakewelchert looks like the footer donate button is still missing its refcode

**Comment by jakewelchert** [comment]
Updated.
